<?php

namespace Database\Seeders;

use App\Models\InventoryCategory;
use App\Models\InventoryItem;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class InventorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::transaction(function () {
            // Status distribution for variety
            $statusOptions = ['SERVICEABLE', 'SERVICEABLE', 'SERVICEABLE', 'SERVICEABLE', 'NEEDS REPAIR', 'UNSERVICEABLE', 'MISSING/LOST'];
            
            $items = [
                [
                    'item_code' => 'INV-LAP-001',
                    'name' => 'Dell Latitude 3420',
                    'description' => '14" laptop for classroom teachers',
                    'category' => 'Laptops',
                    'brand' => 'Dell',
                    'model' => 'Latitude 3420',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 48500,
                    'quantity' => 10,
                    'available_quantity' => 8,
                    'unit_of_measure' => 'pcs',
                    'location' => 'ICT Stockroom',
                    'status' => 'SERVICEABLE',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subMonths(10),
                    'warranty_expiry' => now()->addMonths(14),
                    'supplier' => 'Dell Technologies PH',
                    'notes' => 'Includes Windows 11 Pro and MS Office licenses.',
                ],
                [
                    'item_code' => 'INV-DESK-002',
                    'name' => 'Teacher Desktop Set',
                    'description' => 'i3 desktop bundle with monitor and AVR',
                    'category' => 'Desktop Computers',
                    'brand' => 'Acer',
                    'model' => 'Veriton Essentials',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 37500,
                    'quantity' => 6,
                    'available_quantity' => 4,
                    'unit_of_measure' => 'sets',
                    'location' => 'Admin Office',
                    'status' => 'SERVICEABLE',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subYear(),
                    'warranty_expiry' => now()->addMonths(9),
                    'supplier' => 'Acer Philippines',
                    'notes' => 'Two units currently assigned for grading use.',
                ],
                [
                    'item_code' => 'INV-PROJ-003',
                    'name' => 'Epson XGA Projector',
                    'description' => 'Portable projector for classrooms and events',
                    'category' => 'Projectors',
                    'brand' => 'Epson',
                    'model' => 'EB-X06',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 29500,
                    'quantity' => 4,
                    'available_quantity' => 3,
                    'unit_of_measure' => 'pcs',
                    'location' => 'Library AV Cabinet',
                    'status' => 'SERVICEABLE',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subMonths(6),
                    'warranty_expiry' => now()->addMonths(18),
                    'supplier' => 'Epson Philippines',
                    'notes' => 'Includes spare lamps and ceiling mounts.',
                ],
                [
                    'item_code' => 'INV-SPEAK-004',
                    'name' => 'Multimedia Speaker Set',
                    'description' => 'Powered speakers for presentations',
                    'category' => 'Audio Equipment',
                    'brand' => 'Logitech',
                    'model' => 'Z407',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 6500,
                    'quantity' => 5,
                    'available_quantity' => 5,
                    'unit_of_measure' => 'sets',
                    'location' => 'AV Room',
                    'status' => 'SERVICEABLE',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subMonths(4),
                    'warranty_expiry' => now()->addMonths(20),
                    'supplier' => 'Thinking Tools',
                    'notes' => 'Bluetooth capable; assigned per request.',
                ],
                [
                    'item_code' => 'INV-CAM-005',
                    'name' => 'HD Webcam Kit',
                    'description' => 'Webcam plus tripod for hybrid classes',
                    'category' => 'AV Accessories',
                    'brand' => 'Logitech',
                    'model' => 'C922',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 8500,
                    'quantity' => 8,
                    'available_quantity' => 7,
                    'unit_of_measure' => 'kits',
                    'location' => 'ICT Storage',
                    'status' => 'SERVICEABLE',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subMonths(3),
                    'warranty_expiry' => now()->addMonths(21),
                    'supplier' => 'PC Express',
                    'notes' => 'Tripod + USB extension included.',
                ],
                [
                    'item_code' => 'INV-MAINT-006',
                    'name' => 'Network Switch - 24 Port',
                    'description' => 'Managed switch for ICT lab backbone',
                    'category' => 'Networking',
                    'brand' => 'Cisco',
                    'model' => 'CBS250-24T-4G',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 42000,
                    'quantity' => 2,
                    'available_quantity' => 1,
                    'unit_of_measure' => 'pcs',
                    'location' => 'Server Rack',
                    'status' => 'NEEDS REPAIR',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subMonths(8),
                    'warranty_expiry' => now()->addMonths(16),
                    'supplier' => 'Cisco Partner PH',
                    'notes' => 'One unit undergoing firmware update.',
                ],
                [
                    'item_code' => 'INV-LAP-007',
                    'name' => 'HP ProBook 450 G8',
                    'description' => '15.6" business laptop',
                    'category' => 'Laptops',
                    'brand' => 'HP',
                    'model' => 'ProBook 450 G8',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 52000,
                    'quantity' => 8,
                    'available_quantity' => 6,
                    'unit_of_measure' => 'pcs',
                    'location' => 'ICT Stockroom',
                    'status' => 'SERVICEABLE',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subMonths(5),
                    'warranty_expiry' => now()->addMonths(19),
                    'supplier' => 'HP Philippines',
                    'notes' => 'For administrative staff use.',
                ],
                [
                    'item_code' => 'INV-PRINT-008',
                    'name' => 'Canon PIXMA G3010',
                    'description' => 'Inkjet printer with refillable tanks',
                    'category' => 'Printers',
                    'brand' => 'Canon',
                    'model' => 'PIXMA G3010',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 12500,
                    'quantity' => 3,
                    'available_quantity' => 2,
                    'unit_of_measure' => 'pcs',
                    'location' => 'Admin Office',
                    'status' => 'NEEDS REPAIR',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subMonths(7),
                    'warranty_expiry' => now()->addMonths(17),
                    'supplier' => 'Canon Philippines',
                    'notes' => 'Printer head needs cleaning.',
                ],
                [
                    'item_code' => 'INV-TAB-009',
                    'name' => 'Samsung Galaxy Tab A8',
                    'description' => '10.5" tablet for digital learning',
                    'category' => 'Tablets',
                    'brand' => 'Samsung',
                    'model' => 'Galaxy Tab A8',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 18500,
                    'quantity' => 12,
                    'available_quantity' => 10,
                    'unit_of_measure' => 'pcs',
                    'location' => 'ICT Lab',
                    'status' => 'SERVICEABLE',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subMonths(2),
                    'warranty_expiry' => now()->addMonths(22),
                    'supplier' => 'Samsung Philippines',
                    'notes' => 'For student use in digital classes.',
                ],
                [
                    'item_code' => 'INV-MON-010',
                    'name' => 'LG 24" IPS Monitor',
                    'description' => 'Full HD IPS monitor',
                    'category' => 'Monitors',
                    'brand' => 'LG',
                    'model' => '24MK430H-B',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 8500,
                    'quantity' => 15,
                    'available_quantity' => 12,
                    'unit_of_measure' => 'pcs',
                    'location' => 'ICT Storage',
                    'status' => 'SERVICEABLE',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subMonths(4),
                    'warranty_expiry' => now()->addMonths(20),
                    'supplier' => 'LG Electronics PH',
                    'notes' => 'For desktop computer setups.',
                ],
                [
                    'item_code' => 'INV-PERIPH-011',
                    'name' => 'Logitech MK270 Wireless Combo',
                    'description' => 'Wireless keyboard and mouse set',
                    'category' => 'Peripherals',
                    'brand' => 'Logitech',
                    'model' => 'MK270',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 1200,
                    'quantity' => 20,
                    'available_quantity' => 18,
                    'unit_of_measure' => 'sets',
                    'location' => 'ICT Storage',
                    'status' => 'SERVICEABLE',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subMonths(3),
                    'warranty_expiry' => now()->addMonths(21),
                    'supplier' => 'PC Express',
                    'notes' => 'Bulk purchase for office use.',
                ],
                [
                    'item_code' => 'INV-PROJ-012',
                    'name' => 'BenQ MW560',
                    'description' => 'Portable DLP projector',
                    'category' => 'Projectors',
                    'brand' => 'BenQ',
                    'model' => 'MW560',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 32000,
                    'quantity' => 3,
                    'available_quantity' => 2,
                    'unit_of_measure' => 'pcs',
                    'location' => 'AV Room',
                    'status' => 'SERVICEABLE',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subMonths(6),
                    'warranty_expiry' => now()->addMonths(18),
                    'supplier' => 'BenQ Philippines',
                    'notes' => 'High brightness for well-lit rooms.',
                ],
                [
                    'item_code' => 'INV-AUDIO-013',
                    'name' => 'JBL Flip 6 Portable Speaker',
                    'description' => 'Bluetooth portable speaker',
                    'category' => 'Audio Equipment',
                    'brand' => 'JBL',
                    'model' => 'Flip 6',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 7500,
                    'quantity' => 6,
                    'available_quantity' => 5,
                    'unit_of_measure' => 'pcs',
                    'location' => 'AV Room',
                    'status' => 'SERVICEABLE',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subMonths(2),
                    'warranty_expiry' => now()->addMonths(22),
                    'supplier' => 'JBL Philippines',
                    'notes' => 'Waterproof, for outdoor events.',
                ],
                [
                    'item_code' => 'INV-NET-014',
                    'name' => 'TP-Link AC1200 Router',
                    'description' => 'Dual-band WiFi router',
                    'category' => 'Networking',
                    'brand' => 'TP-Link',
                    'model' => 'Archer C50',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 2500,
                    'quantity' => 8,
                    'available_quantity' => 6,
                    'unit_of_measure' => 'pcs',
                    'location' => 'ICT Storage',
                    'status' => 'SERVICEABLE',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subMonths(5),
                    'warranty_expiry' => now()->addMonths(19),
                    'supplier' => 'TP-Link Philippines',
                    'notes' => 'For classroom WiFi coverage.',
                ],
                [
                    'item_code' => 'INV-DESK-015',
                    'name' => 'Dell OptiPlex 3090',
                    'description' => 'Small form factor desktop PC',
                    'category' => 'Desktop Computers',
                    'brand' => 'Dell',
                    'model' => 'OptiPlex 3090',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 42000,
                    'quantity' => 5,
                    'available_quantity' => 3,
                    'unit_of_measure' => 'pcs',
                    'location' => 'ICT Lab',
                    'status' => 'SERVICEABLE',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subMonths(9),
                    'warranty_expiry' => now()->addMonths(15),
                    'supplier' => 'Dell Technologies PH',
                    'notes' => 'For computer lab stations.',
                ],
                [
                    'item_code' => 'INV-LAP-016',
                    'name' => 'Acer Aspire 5',
                    'description' => '15.6" laptop - damaged screen',
                    'category' => 'Laptops',
                    'brand' => 'Acer',
                    'model' => 'Aspire 5 A515-56',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 35000,
                    'quantity' => 1,
                    'available_quantity' => 0,
                    'unit_of_measure' => 'pcs',
                    'location' => 'Repair Shop',
                    'status' => 'UNSERVICEABLE',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subMonths(12),
                    'warranty_expiry' => now()->addMonths(12),
                    'supplier' => 'Acer Philippines',
                    'notes' => 'Screen cracked, beyond repair.',
                ],
                [
                    'item_code' => 'INV-TAB-017',
                    'name' => 'iPad Air 4th Gen',
                    'description' => '10.9" tablet - missing',
                    'category' => 'Tablets',
                    'brand' => 'Apple',
                    'model' => 'iPad Air 4',
                    'serial_number' => Str::upper(Str::random(10)),
                    'unit_price' => 35000,
                    'quantity' => 1,
                    'available_quantity' => 0,
                    'unit_of_measure' => 'pcs',
                    'location' => 'Unknown',
                    'status' => 'MISSING/LOST',
                    'tracking_mode' => 'detailed',
                    'purchase_date' => now()->subMonths(8),
                    'warranty_expiry' => now()->addMonths(16),
                    'supplier' => 'Apple Philippines',
                    'notes' => 'Reported missing during inventory check.',
                ],
            ];

            // Get categories from database (should be seeded by InventoryCategorySeeder)
            $categories = InventoryCategory::all()->keyBy('name');

            foreach ($items as $itemData) {
                $categoryName = $itemData['category'];
                $category = $categories->get($categoryName);
                
                if (!$category) {
                    $this->command->warn("Category '{$categoryName}' not found. Skipping item {$itemData['item_code']}.");
                    continue;
                }
                
                // Set both category_id (foreign key) and category (string for display/backward compatibility)
                $itemData['category_id'] = $category->id;
                $itemData['category'] = $category->name; // Ensure category string matches the category name
                $itemData['image_path'] = null;
                
                // Ensure tracking_mode is set (already set in array, but ensure it's there)
                if (!isset($itemData['tracking_mode'])) {
                    $itemData['tracking_mode'] = 'detailed';
                }
                
                // Ensure status is one of the new values
                if (!in_array($itemData['status'], ['SERVICEABLE', 'UNSERVICEABLE', 'NEEDS REPAIR', 'MISSING/LOST'])) {
                    $itemData['status'] = 'SERVICEABLE'; // Default to SERVICEABLE if invalid
                }

                InventoryItem::updateOrCreate(
                    ['item_code' => $itemData['item_code']],
                    $itemData
                );
            }
            
            $this->command->info('Inventory items seeded successfully with new status values!');
        });
    }
}

